In [3]:
from Project.ETL_JO import ETL_JO
from pyspark.sql.types import *
from pyspark.sql import SparkSession

In [2]:
AWS_SERVICE_NAME = 's3'
REGION = "ap-northeast-2"

AWS_ACCESS_ID = 'aws_access_key_id'
AWS_SECRET_KEY = 'aws_secret_access_key'
AWS_BUCKET_NAME = 'aws_s3_bucket_name'

In [5]:
etl = ETL_JO()

data = etl._get_data('20230407', AWS_ACCESS_ID, AWS_SECRET_KEY, AWS_BUCKET_NAME, REGION)

In [6]:
data

,idx,PUMMOK,PUMJONG,UUN,DDD,PPRICE,SSANGI,CORP_NM,ADJ_DT,item,bubin
0,1,감귤,감귤 기타,1.5kg,특(1등),17000,제주자치도 제주시,서울청과,20230407,감귤,11000101
1,2,감귤,감귤 기타,1.5kg,특(1등),17000,제주자치도 제주시,서울청과,20230407,감귤,11000101
2,3,감귤,감귤 기타,1.5kg,특(1등),15000,제주자치도 제주시,서울청과,20230407,감귤,11000101
3,4,감귤,금감,10kg,특(1등),48000,제주자치도 서귀포시,서울청과,20230407,감귤,11000101
4,5,감귤,금감,10kg,특(1등),45000,제주자치도 서귀포시,서울청과,20230407,감귤,11000101
...,...,...,...,...,...,...,...,...,...,...,...
26372,665,호박,쥬키니호박,10kg,특(1등),10500,충청남도 논산시,한국청과,20230407,호박,11000105
26373,666,호박,쥬키니호박,10kg,특(1등),10000,충청남도 논산시,한국청과,20230407,호박,11000105
26374,667,호박,쥬키니호박,10kg,특(1등),8000,충청남도 부여군,한국청과,20230407,호박,11000105
26375,668,호박,쥬키니호박,10kg,특(1등),7500,충청남도 부여군,한국청과,20230407,호박,11000105
26376,669,호박,쥬키니호박,10kg,상(2등),5500,충청남도 부여군,한국청과,20230407,호박,11000105

In [7]:
spark_batch = SparkSession.builder.appName('batch_DF').getOrCreate()

In [8]:
df = spark_batch.createDataFrame(data)

c:\Users\wldnr\anaconda3\envs\cp2\lib\site-packages\pyspark\sql\pandas\conversion.py:327: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for column, series in pdf.iteritems():

In [9]:
df.show()

+---+------+---------+-----+-------+------+-------------------+--------+--------+----+--------+
|idx|PUMMOK|  PUMJONG|  UUN|    DDD|PPRICE|             SSANGI| CORP_NM|  ADJ_DT|item|   bubin|
+---+------+---------+-----+-------+------+-------------------+--------+--------+----+--------+
|  1|  감귤|감귤 기타|1.5kg|특(1등)| 17000|  제주자치도 제주시|서울청과|20230407|감귤|11000101|
|  2|  감귤|감귤 기타|1.5kg|특(1등)| 17000|  제주자치도 제주시|서울청과|20230407|감귤|11000101|
|  3|  감귤|감귤 기타|1.5kg|특(1등)| 15000|  제주자치도 제주시|서울청과|20230407|감귤|11000101|
|  4|  감귤|     금감| 10kg|특(1등)| 48000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  5|  감귤|     금감| 10kg|특(1등)| 45000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  6|  감귤|     금감| 10kg|특(1등)| 45000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  7|  감귤|     금감| 10kg|특(1등)| 34000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  8|  감귤|     금감| 10kg|특(1등)| 34000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  9|  감귤|     금감| 10kg|특(1등)| 20000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 10|  감귤|   천혜향| 10kg|특(1등)| 67000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 11|  감귤|   천혜향| 10kg|특(1등)| 66000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 12|  감귤|   천혜향| 10kg|특(1등)| 66000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 13|  감귤|   천혜향| 10kg|특(1등)| 64000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 14|  감귤|   천혜향| 10kg|특(1등)| 64000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 15|  감귤|   천혜향|  9kg|특(1등)| 57000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 16|  감귤|   천혜향| 10kg|특(1등)| 56000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 17|  감귤|   천혜향|  3kg|특(1등)| 23000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 18|  감귤|   카라향| 10kg|특(1등)| 60000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 19|  감귤|   카라향|  3kg|특(1등)| 20000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 20|  감귤|   카라향|  3kg|특(1등)| 20000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
+---+------+---------+-----+-------+------+-------------------+--------+--------+----+--------+
only showing top 20 rows

In [14]:
def EDA(spark_dataframe):
    re_list1 = ['감귤(기타)', '감귤(하우스)', '감귤 기타', '만다린(수)', '감자(기타)', '감자(수입)', '감자(단오)', '감자(조풍)', '감자수입', '딸기(기타)', '딸기', '딸기기타', '흰딸기', '버섯', '버섯기타', '사과', '후브락스(사과)', '사과(기타)', '가지고추', '퍼펙트고추', '블랙망고수박']
    re_list2 = ['카라향', '천혜향']
    re_list3 = ['금감']

    spark_dataframe = spark_dataframe.replace(re_list1, '기타', 'PUMJONG')
    spark_dataframe = spark_dataframe.replace(re_list2, '향', 'PUMJONG')
    spark_dataframe = spark_dataframe.replace(re_list3, 'replace 테스트', 'PUMJONG')

    return spark_dataframe

In [15]:
df_test = EDA(df)
df_test.show()

+---+------+--------------+-----+-------+------+-------------------+--------+--------+----+--------+
|idx|PUMMOK|       PUMJONG|  UUN|    DDD|PPRICE|             SSANGI| CORP_NM|  ADJ_DT|item|   bubin|
+---+------+--------------+-----+-------+------+-------------------+--------+--------+----+--------+
|  1|  감귤|          기타|1.5kg|특(1등)| 17000|  제주자치도 제주시|서울청과|20230407|감귤|11000101|
|  2|  감귤|          기타|1.5kg|특(1등)| 17000|  제주자치도 제주시|서울청과|20230407|감귤|11000101|
|  3|  감귤|          기타|1.5kg|특(1등)| 15000|  제주자치도 제주시|서울청과|20230407|감귤|11000101|
|  4|  감귤|replace 테스트| 10kg|특(1등)| 48000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  5|  감귤|replace 테스트| 10kg|특(1등)| 45000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  6|  감귤|replace 테스트| 10kg|특(1등)| 45000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  7|  감귤|replace 테스트| 10kg|특(1등)| 34000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  8|  감귤|replace 테스트| 10kg|특(1등)| 34000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
|  9|  감귤|replace 테스트| 10kg|특(1등)| 20000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 10|  감귤|            향| 10kg|특(1등)| 67000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 11|  감귤|            향| 10kg|특(1등)| 66000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 12|  감귤|            향| 10kg|특(1등)| 66000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 13|  감귤|            향| 10kg|특(1등)| 64000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 14|  감귤|            향| 10kg|특(1등)| 64000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 15|  감귤|            향|  9kg|특(1등)| 57000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 16|  감귤|            향| 10kg|특(1등)| 56000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 17|  감귤|            향|  3kg|특(1등)| 23000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 18|  감귤|            향| 10kg|특(1등)| 60000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 19|  감귤|            향|  3kg|특(1등)| 20000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
| 20|  감귤|            향|  3kg|특(1등)| 20000|제주자치도 서귀포시|서울청과|20230407|감귤|11000101|
+---+------+--------------+-----+-------+------+-------------------+--------+--------+----+--------+
only showing top 20 rows